Feature/intial_setup
LssPolymerElements/titanium-csv-import-export-tool pull request #1
Opened 2017-08-30 22:11 UTC by rhettshipp

2017-08-31 16:23 UTC, gfportfolio commented on bower.json
> +    "iron-iconset-svg": "polymerelements/iron-iconset-svg#^2.0.0",
polymer is not Caps

2017-08-31 16:23 UTC, gfportfolio commented on csv-file-export-button.js
> +var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
.js can be in the git ignore

2017-08-31 16:23 UTC, gfportfolio commented on tsconfig.json
> +    "target": "es2015",
Target ES6

2017-08-31 16:23 UTC, gfportfolio commented on tsconfig.json
> +    "target": "es2015",
Also know as es2017

2017-08-31 16:23 UTC, gfportfolio commented on bower.json
> +    "iron-demo-helpers": "PolymerElements/iron-demo-helpers#^2.0.0",
Missing Toast here   "paper-toast": "PolymerElements/paper-toast#^2.0.0",
It also needs to be in the titanium-csv-import-export-tool.html

2017-08-31 16:39 UTC, rhettshipp commented on bower.json
> +    "iron-iconset-svg": "polymerelements/iron-iconset-svg#^2.0.0",
Addressed

2017-08-31 16:39 UTC, rhettshipp commented on bower.json
> +    "iron-demo-helpers": "PolymerElements/iron-demo-helpers#^2.0.0",
Addressed

2017-08-31 16:39 UTC, rhettshipp commented on csv-file-export-button.js
> +var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
Addressed

2017-08-31 16:39 UTC, rhettshipp commented on tsconfig.json
> +    "target": "es2015",
Addressed

2017-08-31 20:20 UTC, visum commented on csv-file-export-button.ts
> +        raisedValue = raisedValue === '' ? true : raisedValue;
This looks suspect, raisedValue is true if raised is an empty string?  I would intuit that empty would be false.

2017-08-31 20:20 UTC, visum commented on csv-file-export-button.ts
> +        raisedValue = raisedValue === '' ? true : raisedValue;
Unless we're looking at a boolean HTML attribute, I suppose.

2017-08-31 20:20 UTC, visum commented on csv-file-import-button.ts
> +    async handleFileSelect(event: any) {
Can this be anything but an Event type? It is handled as an Event below, is it necessary to cast it as :any?

2017-08-31 20:20 UTC, visum commented on csv-file-import-button.ts
> +    removeDisabled(value: any) {
removeDisabled(true) doesn't make much sense, rename to setDisabled and accept a :boolean instead of :any?

2017-08-31 20:20 UTC, visum commented on csv-file-import-button.ts
> +    handleDragOver(event: any) {
cast again

2017-08-31 20:20 UTC, visum commented on csv-file-import-button.ts
> +    removeDisabled(value: any) {
Even better is probably setEnabled(), favoring positives over negatives (even though HTML favors negatives)

2017-08-31 20:20 UTC, visum commented on csv-file-import-button.ts
> +        return !((('draggable' in div) || ('ondragstart' in div && 'ondrop' in div)) && 'FormData' in window && 'FileReader' in window);
a pretty obtuse line, I'd prefer breaking each of the grouped parts becoming variables.

2017-08-31 20:20 UTC, visum commented on titanium-csv-import-export-tool.ts
> +                            errorText += `${err.message}`;
A possible alternative:

`let errorText = results.errors.map((err) => {return err.message;}).join("");`

2017-08-31 20:20 UTC, visum commented on titanium-csv-import-export-tool.ts
> +    checkAndToastErrorMessage(csvMessage: ICSVMessageResult): ICSVMessageResult {
A function with "and" in its name is a red flag because it says the function is doing two things. Might be better to do the ApplicationError check outside and let this just do the toasting.

2017-08-31 20:20 UTC, visum commented on titanium-csv-import-export-tool.ts
> +                if (parseInt(eachRawCSVRow[keyIndex]).toString() === eachRawCSVRow[keyIndex]) {
parseInt should always include the radix argument, else odd things happen.

2017-08-31 20:20 UTC, visum commented on titanium-csv-import-export-tool.ts
> +                    returnRow[eachKey] = parseInt(eachRawCSVRow[keyIndex]);
radix on parseInt

2017-08-31 20:20 UTC, visum commented on gulpfile.js
> +var gulp = require('gulp');
adding .js to gitignore will also ignore this gulpfile, is that desired?

2017-08-31 20:20 UTC, visum commented on titanium-csv-import-export-tool.ts
> +                if (parseInt(eachRawCSVRow[keyIndex]).toString() === eachRawCSVRow[keyIndex]) {
What's the purpose of parsing the cell to an int, making it a string and comparing it with its original value? Are you verifying it's a valid int? If so, 
`isNan(parseInt(field, 10))`
is probably what you're after.

Also keep in mind parseInt's big brother, parseFloat which is always base 10 and handles decimals.

2017-08-31 20:20 UTC, visum commented on titanium-csv-import-export-tool.ts
> +                    returnRow[eachKey] = parseInt(eachRawCSVRow[keyIndex]);
parseFloat()?

2017-08-31 20:20 UTC, visum commented on titanium-csv-import-export-tool.ts
> +                if (eachRow[eachKey] === null || !eachRow[eachKey]) {
null is false-y, do we need the first comparison here?

2017-08-31 20:20 UTC, visum commented on titanium-csv-import-export-tool.ts
> +        let invalidSizeError: CSVMessage = { message: `The uploaded file does not have the expected amount of columns. The expected number of columns is ${columnSize}`, lines: [] };
"The uploaded file was expected to have ${columnSize} columns, but does not."

2017-08-31 20:20 UTC, visum commented on titanium-csv-import-export-tool.ts
> +                        return true;  // Both thisModel[key] and csvRow[key] are falsey
Good comments

2018-02-02 18:35 UTC, gfportfolio requested changes
Removing from my list, we will no longer be making this component.

2018-02-27 16:14 UTC, closed without merging